export const CHANGE_FORM = 'APP/REGISTRATION/CHANGE';

export const REGISTRATION = 'APP/REGISTERFORM/LOGIN';
export const REGISTRATION_PENDING = 'APP/REGISTERFORM/LOGIN_PENDING';
export const REGISTRATION_SUCCESS = 'APP/REGISTERFORM/LOGIN_SUCCESS';
export const REGSITRATION_FAILED = 'APP/REGISTERFORM/LOGIN_FAILED';