export const CHANGE_FORM = 'APP/LOGIN/CHANGE';

export const LOGIN = 'APP/LOGINFORM/LOGIN';
export const LOGIN_PENDING = 'APP/LOGINFORM/LOGIN_PENDING';
export const LOGIN_SUCCESS = 'APP/LOGINFORM/LOGIN_SUCCESS';
export const LOGIN_FAILED = 'APP/LOGINFORM/LOGIN_FAILED';
